name: Run Project Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.1
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.1
      - name: Testing
        run: unittest